accounts/urls.py
from django.urls import path
from . import views
from accounts.views import *
#from accounts.views import signupView, loginView, logoutUser, ChangeProfileView, account_activation_sent_view
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView, PasswordResetDoneView
from django.contrib.auth import views as auth_views

app_name = 'accounts'


urlpatterns = [

    path('', loginView.as_view(), name='login'),
    # path('', views.loginView, name='login'),

    path('activate/<uidb64>/<token>',
         views.account_activate.as_view(), name='activate'),

    path('register/', signupView.as_view(), name='register'),

    # path('logout/', logoutView.as_view(), name='logout'),
    path("logout", views.logout_request, name= "logout"),
    
   # path("logout/", views.logoutUser, name="logout"),

    path('password_reset/', PasswordResetView.as_view(
        template_name='accounts/partials/password_reset.html',
        email_template_name='accounts/email/password_reset.txt',
        html_email_template_name='accounts/email/password_reset_email.html',
        subject_template_name='accounts/email/password_reset_subject.txt'
    ), name='password_reset'),

    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='accounts/partials/password_reset_done.html',
        ),
        name='password_reset_done'),

    path(
        'password_reset/<str:uidb64>/<str:token>/',
        PasswordResetConfirmView.as_view(
            template_name='accounts/partials/password_reset_confirm.html',
        ),
        name='password_reset_confirm'),

    path(
        'password_reset/complete/',
        PasswordResetCompleteView.as_view(
            template_name='accounts/partials/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
    path('change_profile', views.ChangeProfileView, name='change_profile'),
]

documenterapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('documenter/', include('documenter.urls', namespace='documenter')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser, BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model, login
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _
from django.core.mail import send_mail

from accounts.managers import CustomUserManager
from django_countries.fields import CountryField


# Create your models here.

# class CustomUser(AbstractUser):

#     email = models.EmailField(_('email address'), unique=True)
#     first_name = models.CharField(max_length=150, unique=True)
#     last_name = models.CharField(max_length=150, blank=True)
#     about = models.TextField(_('about'), max_length=500, blank=True)
#     country = CountryField()

#     # User Status
#     is_active = models.BooleanField(default=False)
#     signup_confirmation = models.BooleanField(default=False)
#     is_staff = models.BooleanField(default=False)
#     created = models.DateTimeField(auto_now_add=True)
#     updated = models.DateTimeField(auto_now=True)
#     class Meta:
#         verbose_name = _("user")
#         verbose_name_plural = _("users")

#     username = None
#     email = models.EmailField(_("email address"), unique=True)

#     USERNAME_FIELD = "email"
#     REQUIRED_FIELDS = []

#     objects = CustomUserManager()

#     def __str__(self):
#         return self.email


class CustomUser(AbstractBaseUser, PermissionsMixin):
    
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150, blank=True)
    about = models.TextField(_('about'), max_length=500, blank=True)
    country = CountryField()

    # User Status
    is_active = models.BooleanField(default=False)
    signup_confirmation = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "accounts"
        verbose_name_plural = "accounts"

    # def __str__(self):
    #     return self.first_name

accounts/forms.py
from django import forms
from django.forms import ValidationError
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, ReadOnlyPasswordHashField
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm, SetPasswordForm
#from django.contrib.auth.models import User

from accounts.models import CustomUser
from accounts.models import *
from django.contrib.auth import get_user_model, password_validation

User = get_user_model()

class SignUpForm(UserCreationForm):
    #username = forms.CharField(max_length=30, required=True, help_text='Username.')
    first_name = forms.CharField(max_length=30, required=True, help_text='Fisrt Name.')
    last_name = forms.CharField(max_length=30, required=True, help_text='Last Name.')
    email = forms.EmailField(max_length=100, help_text='Required', error_messages={'required': 'Sorry, you will need an email'})
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email', 'password', 'password2']

    
        # def clean_email(self):
        #     """Ensure email uniqueness."""
        #     email = self.cleaned_data.get('email')
        #     qs = User.objects.filter(email=email)
        #     if qs.exists():
        #         raise forms.ValidationError("Email Already Exist")
        #     return email

        # def clean_password2(self):
        #         cd = super().clean()
        #         password = cd.get("password")
        #         password2 = cd.get("password2")

        #         if password is not None and password != password2:
        #             raise forms.ValidationError('Passwords don\'t match.')
        #         return cd
    
# class UserAdminCreationForm(forms.ModelForm):
#     #     first_name = forms.CharField(max_length=30, required=True, help_text='Fisrt Name.')
#     #     last_name = forms.CharField(max_length=30, required=True, help_text='Last Name.')
#     #  # username = forms.EmailField(max_length=254, required=True, help_text='Required. Input a valid email address.')
#     #     password1 = forms.CharField(widget=forms.PasswordInput)
#     #     password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

#         class Meta:
#             model = CustomUser
#             fields = ['email']
        
#         def clean_password2(self):
#             cd = super().clean()
#             password = cd.get("password")
#             password2 = cd.get("password2")

#             if password is not None and password != password2:
#                 raise forms.ValidationError('Passwords don\'t match.')
#             return cd
        
#         def save(self, commit=True):
#             user = super().save(commit=False)
#             user.set_password(self.cd["password"])

#             if commit:
#                 user.save()
#             return user


class LoginForm(AuthenticationForm):
    
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'Registered Email'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Password'
        }
    ))
class PwdResetForm(PasswordResetForm):
    
    email = forms.EmailField(max_length=254, help_text='Required. Input a valid email address.')

    def clean_email(self):
        email = self.cleaned_data['email']
        u = User.objects.filter(email=email)
        if not u:
            raise forms.ValidationError(
                'Unfortunatley we can not find that email address')
        return email

class PwdResetConfirmForm(SetPasswordForm):
    new_password = forms.CharField(
        label='New password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password'}))
    new_password2 = forms.CharField(
        label='Repeat password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password'}))


class UserEditForm(forms.ModelForm):
    
    email = forms.EmailField(
        label='Account email (can not be changed)', max_length=200, widget=forms.TextInput(
            attrs={'placeholder': 'email', 'readonly': 'readonly'}))

    first_name = forms.CharField(
        label='Firstname', min_length=4, max_length=50, widget=forms.TextInput(
            attrs={'placeholder': 'Username','readonly': 'readonly'}))

    last_name = forms.CharField(
        label='Lastname', min_length=4, max_length=50, widget=forms.TextInput(
            attrs={'placeholder': 'Firstname'}))

    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['email'].required = True

accounts/views.py
from django.shortcuts import render, redirect 
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.sites.shortcuts import get_current_site

from django.contrib.auth.forms import UserCreationForm
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from accounts.token import account_activation_token

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View, FormView
from validate_email import validate_email
from django.urls import reverse

from django.contrib.auth import get_user_model, login
from django.core.mail import EmailMessage
from django.template.loader import render_to_string

from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from accounts.models import *
from accounts.forms import SignUpForm, LoginForm, UserEditForm

User = get_user_model()

######################################################################################
class signupView(View):
    def get(self, request):
        return render(request, 'accounts/partials/register.html')

    def post(self, request):
        context = {
            'data': request.POST,
            'has_error': False
        }

        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')
        if len(password) < 6:
            messages.add_message(request, messages.ERROR,
                                 'passwords should be atleast 6 characters long')
            context['has_error'] = True
        if password != password2:
            messages.add_message(request, messages.ERROR,
                                 'passwords dont match')
            context['has_error'] = True

        if not validate_email(email):
            messages.add_message(request, messages.ERROR,
                                 'Please provide a valid email')
            context['has_error'] = True

        try:
            if User.objects.get(email=email):
                messages.add_message(request, messages.ERROR, 'Email already registered by another user')
                context['has_error'] = True

        except Exception as identifier:
            pass

        if context['has_error']:
            return render(request, 'accounts/partials/register.html', context, status=400)

        user = User.objects.create_user(email=email, password = password)
        user.set_password(password)
        user.last_name = last_name
        user.is_active = False
        user.save()

        current_site = get_current_site(request)
        subject = 'Active your Account'
        message = render_to_string('accounts/partials/account_activation_email.html',
                                   {
                                       'user': user,
                                       'domain': current_site.domain,
                                       'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                                       'token': account_activation_token.make_token(user)
                                   }
                                   )
 
        to_email = request.POST.get('email')  
        email = EmailMessage(  
                subject, message, to=[to_email]  
                )  

        if not context['has_error']:
            email.send()
            messages.add_message(request, messages.SUCCESS,'We sent you an email to verify your account')
            #return render(request, 'accounts/partials/account_activation_sent.html')

        return redirect('accounts:login')


####################################################################################
# class logoutView(View):
#     def post(self, request):
#         logout(request)
#         messages.add_message(request, messages.SUCCESS, 'Successfully logged out')
#         return redirect('accounts:login')

####################################################################################
def logout_request(request):
        logout(request)
        messages.info(request, "You have successfully logged out.") 
        return redirect("accounts:login")

###################################################################################################

#Validation that user exist during login if not it should display associated error of user not existing.

#########################################################################

class loginView(View):
    def get(self, request):
        return render(request, 'accounts/partials//login.html')

    def post(self, request):
        context = {
            'data': request.POST,
            'has_error': False
        }
        email = request.POST.get('email')
        password = request.POST.get('password')
        if email == '':
            messages.add_message(request, messages.ERROR,
                                 'Email is required')
            context['has_error'] = True
        if password == '':
            messages.add_message(request, messages.ERROR,
                                 'Password is required')
            context['has_error'] = True
        user = authenticate(request, email=email, password=password)

        if not user and not context['has_error']:
            messages.add_message(request, messages.ERROR, 'Invalid login')
            context['has_error'] = True

        if context['has_error']:
            return render(request, 'accounts/partials/login.html', context=context)
        login(request, user)
        #return redirect('documenter:home')
        return render(request, 'documenter/_partials/searchResult.html', context=context)


@login_required
class ChangeProfileView(LoginRequiredMixin, FormView):
    template_name = 'accounts/partials/userprofile.html'
    form_class = UserEditForm

    def get_initial(self):
        user = self.request.user
        initial = super().get_initial()
        initial['first_name'] = user.first_name
        initial['last_name'] = user.last_name
        return initial

    def form_valid(self, form):
        user = self.request.user
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.save()

        messages.success(self.request, ('Profile data has been successfully updated.'))

        return redirect('accounts:change_profile')


def account_activation_sent_view(request):
    return render(request, 'accounts/partials/account_activation_sent.html')

class account_activate(View):
    def get(self, request, uidb64, token):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except Exception as identifier:
            user = None
        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            messages.add_message(request, messages.SUCCESS,
                                 'account activated successfully')
            return redirect('accounts:login')
        return render(request, 'accounts/partials/account_activation_invalid.html', status=401)

accounts/templates/accounts/partials/account_activation_email.html
  
{% autoescape off %}

Hi {{ user.last_name }},

Your account has successfully created. Please click below link to activate your account

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}

{% endautoescape %}

accounts/templates/accounts/partials/account_activation_invalid.html
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Invalid Email Activation</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style type="text/css">
  
    @media screen {
    @font-face {
      font-family: 'Source Sans Pro';
      font-style: normal;
      font-weight: 400;
      src: local('Source Sans Pro Regular'), local('SourceSansPro-Regular'), url(https://fonts.gstatic.com/s/sourcesanspro/v10/ODelI1aHBYDBqgeIAH2zlBM0YzuT7MdOe03otPbuUS0.woff) format('woff');
    }

    @font-face {
      font-family: 'Source Sans Pro';
      font-style: normal;
      font-weight: 700;
      src: local('Source Sans Pro Bold'), local('SourceSansPro-Bold'), url(https://fonts.gstatic.com/s/sourcesanspro/v10/toadOcfmlt9b38dHJxOBGFkQc6VGVFSmCnC_l7QZG60.woff) format('woff');
    }
  }

  /**
   * Avoid browser level font resizing.
   * 1. Windows Mobile
   * 2. iOS / OSX
   */
  body,
  table,
  td,
  a {
    -ms-text-size-adjust: 100%; /* 1 */
    -webkit-text-size-adjust: 100%; /* 2 */
  }

  /**
   * Remove extra space added to tables and cells in Outlook.
   */
  table,
  td {
    mso-table-rspace: 0pt;
    mso-table-lspace: 0pt;
  }

  /**
   * Better fluid images in Internet Explorer.
   */
  img {
    -ms-interpolation-mode: bicubic;
  }

  /**
   * Remove blue links for iOS devices.
   */
  a[x-apple-data-detectors] {
    font-family: inherit !important;
    font-size: inherit !important;
    font-weight: inherit !important;
    line-height: inherit !important;
    color: inherit !important;
    text-decoration: none !important;
  }

  /**
   * Fix centering issues in Android 4.4.
   */
  div[style*="margin: 16px 0;"] {
    margin: 0 !important;
  }

  body {
    width: 100% !important;
    height: 100% !important;
    padding: 0 !important;
    margin: 0 !important;
  }

  /**
   * Collapse table borders to avoid space between cells.
   */
  table {
    border-collapse: collapse !important;
  }

  a {
    color: #1a82e2;
  }

  img {
    height: auto;
    line-height: 100%;
    text-decoration: none;
    border: 0;
    outline: none;
  }
  </style>

</head>
<body style="background-color: #e9ecef;">



  <!-- start body -->
  <table border="0" cellpadding="0" cellspacing="0" width="100%">

    <!-- start logo -->
    <tr>
      <td align="center" bgcolor="#e9ecef">
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
          <tr>
            <td align="center" valign="top" style="padding: 36px 24px;">
              <a>
                <img src="accounts/static/images/email-64.png" alt="Logo" border="0" width="48" style="display: block; width: 48px; max-width: 48px; min-width: 48px;">
              </a>
            </td>
          </tr>
        </table>
        
      </td>
    </tr>
    <!-- end logo -->

    <!-- start hero -->
    <tr>
      <td align="center" bgcolor="#e9ecef">
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
          <tr>
            <td align="left" bgcolor="#ffffff" style="padding: 36px 24px 0; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; border-top: 3px solid #d4dadf;">
              <h1 style="margin: 0; font-size: 32px; font-weight: 700; letter-spacing: -1px; line-height: 48px;">Activation Email Error</h1>
            </td>
          </tr>
        </table>
        
      </td>
    </tr>
    <!-- end hero -->

    <!-- start copy block -->
    <tr>
      <td align="center" bgcolor="#e9ecef">
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">

          <!-- start copy -->
          <tr>
            <td align="left" bgcolor="#ffffff" style="padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px;">
              <p style="margin: 0;"> Sorry your email activation is Invalid. Kindly make a request for another validation session</p>
            </td>
          </tr>
          <!-- end copy -->

          <!-- start button -->
          <tr>
            <td align="left" bgcolor="#ffffff">
              <table border="0" cellpadding="0" cellspacing="0" width="100%">
                <tr>
                  <td align="center" bgcolor="#ffffff" style="padding: 12px;">
                    <table border="0" cellpadding="0" cellspacing="0">
                      <tr>
                        <td align="center" bgcolor="#1a82e2" style="border-radius: 6px;">
                          <a href="home.html" target="_blank" style="display: inline-block; padding: 16px 36px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; color: #ffffff; text-decoration: none; border-radius: 6px;">Re-Validate</a>
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
       
      </td>
    </tr>
    <!-- end copy block -->

    <!-- start footer -->
    <tr>
      <td align="center" bgcolor="#e9ecef" style="padding: 24px;">
        
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
        </table>
       
      </td>
    </tr>
    <!-- end footer -->

  </table>
  <!-- end body -->

</body>
</html>

accounts/templates/accounts/partials/login.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login - Documenter</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}">
	<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
	<link rel="stylesheet" href="{% static 'vendor/animate/animate.css' %}">
	<link rel="stylesheet" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
	<link rel="stylesheet" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
	<link rel="stylesheet" href="{% static 'vendor/select2/select2.min.css' %}">
	<link rel="stylesheet" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
	<link rel="stylesheet" href="{% static 'css/nav.css' %}">
	<link rel="stylesheet" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-t-50 p-b-90">

				<form method="POST" class="login100-form validate-form flex-sb flex-w" action="{% url 'accounts:login' %}">
					{% csrf_token %}
					<span class="login100-form-title p-b-51">
						Login
					</span>

						{% if form.errors %}
							<div class="alert alert-primary" role="alert">
								Error: Username or Password not correct!
							</div>
						{% endif %}

					<div class="wrap-input100 validate-input m-b-16" data-validate = "Email is required">
						<input class="input100" type="text" name="email" placeholder="User Email">
						<span class="focus-input100"></span>
					</div>
					
					
					<div class="wrap-input100 validate-input m-b-16" data-validate = "Password is required">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100"></span>
					</div>
					
					<div class="flex-sb-m w-full p-t-3 p-b-24">
						<div class="contact100-form-checkbox">
							<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
							<label class="label-checkbox100" for="ckb1">
								Remember me
							</label>
						</div>

						<div>
							<a href="{% url 'accounts:password_reset' %}" class="txt1">
								Forgot Password?
							</a>
						</div>
					</div>

					<div class="container-login100-form-btn m-t-17">
						<button class="login100-form-btn">
							Login
						</button>
					</div>
					
					<div "mt-6">
						Don't have an account? 
					</div>
					<div >
							<a href="{% url 'accounts:register' %}" class="txt1">
								Create One
							</a>
					</div>

				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	

    <script src="{% static 'js/main2.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
    <script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
    <script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>

</body>
</html>

accounts/templates/accounts/partials/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Register</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}">
	<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
	<link rel="stylesheet" href="{% static 'vendor/animate/animate.css' %}">
	<link rel="stylesheet" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
	<link rel="stylesheet" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
	<link rel="stylesheet" href="{% static 'vendor/select2/select2.min.css' %}">
	<link rel="stylesheet" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
	<link rel="stylesheet" href="{% static 'css/nav.css' %}">
	<link rel="stylesheet" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-t-50 p-b-90">
				
				<form method="POST" class="login100-form validate-form flex-sb flex-w" action="{% url 'accounts:register' %}" >
					{% csrf_token %}
					<span class="login100-form-title p-b-51">
						Register
					</span>

					{% if messages %}
					  <div class="messages">
						{% for message in messages %}
						<div {% if message.tags %} class="alert alert-sm alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
						{% endfor %}
					 </div>
					{% endif %}

                    <div class="wrap-input100 validate-input m-b-16" data-validate = "">
						<input class="input100" type="text" name="first_name" placeholder="Enter First Name">
						<span class="focus-input100"></span>
						
					</div>

					<div class="wrap-input100 validate-input m-b-16" data-validate = "">
						<input class="input100" type="text" name="last_name" placeholder="Enter Last Name">
						<span class="focus-input100"></span>
						
					</div>

					<div class="wrap-input100 validate-input m-b-16" data-validate = "Email is required">
						<input class="input100" type="text" name="email" placeholder="Enter Email">
						<span class="focus-input100"></span>
						
					</div>

					
					<div class="wrap-input100 validate-input m-b-16" data-validate = "Password is required">
						<input class="input100" type="password" name="password" placeholder="Enter Password">
						<span class="focus-input100"></span>
						
					</div>

					<div class="wrap-input100 validate-input m-b-16" data-validate = "Password is required">
						<input class="input100" type="password" name="password2" placeholder="Repeat Password">
						<span class="focus-input100"></span>
						
					</div>
					
					<div class="flex-sb-m w-full p-t-3 p-b-24">
						<div class="contact100-form-checkbox">
							<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
							<label class="label-checkbox100" for="ckb1">
								Remember me
							</label>
						</div>

						<div>
							<a href="{% url 'accounts:login' %}" class="txt1">
								Already Registered?
							</a>
						</div>
					</div>

					<div class="container-login100-form-btn m-t-17">
						<button class="login100-form-btn">
							Register
						</button>
					</div>

				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	

    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
    <script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
    <script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>

</body>
</html>