accounts/urls.py
from django.urls import path
from . import views
from accounts.views import *
#from accounts.views import signupView, loginView, logoutUser, ChangeProfileView, account_activation_sent_view
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView, PasswordResetDoneView
from django.contrib.auth import views as auth_views

app_name = 'accounts'


urlpatterns = [

    path('', loginView.as_view(), name='login'),
    # path('', views.loginView, name='login'),

    path('activate/<uidb64>/<token>',
         views.account_activate.as_view(), name='activate'),

    path('register/', signupView.as_view(), name='register'),

    # path('logout/', logoutView.as_view(), name='logout'),
    path("logout", views.logout_request, name= "logout"),
    
   # path("logout/", views.logoutUser, name="logout"),

    path('password_reset/', PasswordResetView.as_view(
        template_name='accounts/partials/password_reset.html',
        email_template_name='accounts/email/password_reset.txt',
        html_email_template_name='accounts/email/password_reset_email.html',
        subject_template_name='accounts/email/password_reset_subject.txt'
    ), name='password_reset'),

    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='accounts/partials/password_reset_done.html',
        ),
        name='password_reset_done'),

    path(
        'password_reset/<str:uidb64>/<str:token>/',
        PasswordResetConfirmView.as_view(
            template_name='accounts/partials/password_reset_confirm.html',
        ),
        name='password_reset_confirm'),

    path(
        'password_reset/complete/',
        PasswordResetCompleteView.as_view(
            template_name='accounts/partials/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
    path('change_profile', views.ChangeProfileView, name='change_profile'),
]

documenter/urls.py
from django.urls import path
from . import views
from django.views.generic import View
from django.contrib.auth.decorators import login_required

from documenter.views import *


urlpatterns = [
    path('home/', views.homeView, name='home'),
    # path('search/', views.searchView, name='search'),
    path('result/', views.SearchView, name='result'),
    path('details/', views.SearchDetails, name='details'),
    # path('document', views.DocumenterView, name='document'),
    path('document', views.DocumenterView, name='document'),
]

app_name = 'documenter'

documenterapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('documenter/', include('documenter.urls', namespace='documenter')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

documenter/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import User
from accounts.managers import CustomUserManager
from accounts.models import CustomUser
from taggit.managers import TaggableManager
from django.urls import reverse

# Create your models here.
class Searcher (models.Model):
    title = models.CharField(max_length=250, default=None)
    slug = models.SlugField(max_length=250, unique_for_date='created', default=None)
    description = models.TextField(default=None)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    solution_image = models.ImageField(default=None)
    author = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None)
    tags = TaggableManager()
    

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title
    
    def get_full_name(self):
        return f'{self.first_name}+{self.last_name}'
    
    def get_absolute_url(self):
            return reverse('title:description', args=[self.created.year, self.created.month, self.created.day, self.slug])

documenter/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from documenter.models import Searcher
from accounts.models import CustomUser

User = get_user_model()

class SearchForm(ModelForm):
    query = forms.CharField()

class DocumentForm(ModelForm):
    class Meta:
        model = Searcher
        field = '__all__'
        exclude = ['slug']
       # field_classes = {'slug': slug,}





# SearchForm, DocumentationForm | Title, Tag, Description, Images#

documenter/views.py
from django.db.models import Count, Q
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from documenter.models import Searcher
from documenter.forms import SearchForm, DocumentForm
from taggit.models import Tag


# Solution Author Information

# def get_author(user):
#     qs = Author.objects.filter(user=user)
#     if qs.exists():
#         return qs[0]
#     return None


@login_required
def homeView(request):
    if not request.user.is_authenticated:
        return render(request, 'documenter/_partial/home.html')
    elif not request.user.is_authenticated:
        return redirect('accounts:register')
###################################################################
# def document_search():
#     form = SearchForm()
#     query = None
#     result = []
#     if 'query' in request.GET:
#         form = SearchForm(request.GET)
#         if form.is_valid():
#             query = form.cleaned_data['query']
#             results = Searcher.objects.annotate(search=SearchVector('title', 'description', 'tags'),).filter(search=query) 


# def get_queryset(self):
#         query = self.request.GET.get('q')
#         object_list = Searcher.objects.annotate(
#             search=SearchVector('title', 'description', 'tags'),
#         ).filter(search=query)
#         return object_list







##################################################################

# @login_required
# class searchView(View):
#     def get(self, request, *args, **kwargs):
#         queryset = Searcher.objects.all()
#         query = request.GET.get('q')
#         if query:
#             queryset = queryset.filter(
#                 Q(title__icontains=query) |
#                 Q(description__icontains=query)
#             ).distinct()
#         context = {'queryset': queryset}
#         return render(request, 'documenter/_partials/searchResult.html', context) 

# def search(request):
#     queryset = Searcher.objects.all()
#     query = request.GET.get('q')
#     if query:
#         queryset = queryset.filter(
#             Q(title__icontains=query) |
#             Q(description__icontains=query)
#         ).distinct()
#     context = {
#         'queryset': queryset
#     }
#     return render(request, '_partials/searchResult.html', context)
####################################################################################
@login_required
class SearchView(ListView):
    model = Searcher
    context_object_name = 'searches'
    paginate_by = 10
    template_name = 'documenter/_partials/searchResult.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            result = Searcher.objects.annotate(search=SearchVector('title', 'description', 'tags'),).filter(search=query)
            if not result:
                messages.INFO(self.request, 'There was no result for the "{}".'.format(query))
            else:
                messages.SUCCESS(self.request, 'Search result for "{}".'.format(query))
            return result




###################################################################################

# @login_required
# class SearchResultView(ListView):
#     model = Searcher
#     context_object_name = 'searches'
#     paginate_by = 10
#     template_name = 'documenter/_partials/searchResult.html'

# def get_queryset(self, tag_slug=None):
#     query = self.request.GET.get('q')
#     tag = None

#     if tag_slug:
#         tag = get_object_or_404(Tag, slug=tag_slug)
#         object_list = Searcher.filter(tags__in=[tag])

#     paginator = Paginator(object_list, 10) # 10 search result in each page
#     page = self.request.GET.get('page')

#     if query:
#         searchResult = Searcher.objects.all()

#     try:
#         searchResult = paginator.page(page)
#     except PageNotAnInteger:
#         # If page is not an integer deliver the first page
#         searchResult = paginator.page(1)
#     except EmptyPage:
#         # If page is out of range deliver last page of results
#         searchResult = paginator.page(paginator.num_pages)
#     return render(request,
#                  'documenter/_partials/searchResult.html',
#                  {'page': page,
#                   'searchResult': searchResult,
#                   'tag': tag})


@login_required

class SearchDetails(DetailView):
    model = Searcher
    template_name = 'documenter/_partials/landing.html'

@login_required
class DocumenterView(CreateView):
    model = Searcher
    template_name = "documenter/_partials/documenter.html"

documenter/templates/documenter/_partials/base.html
{%load static%}
{%load assets%}


<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block title %}{% endblock %}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href={% static 'images/icons/favicon.ico' %}/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'assets/css/main.css' %}>
    <link rel="stylesheet" type="text/css" href={% static 'assets/css/utils.css' %}>
    <link rel="stylesheet" type="text/css" href={% static 'assets/css/nav.css' %}>
    <link rel="stylesheet" type="text/css" href={% assets 'assets/css/main.css' %}>
<!--===============================================================================================-->
</head>
<body>

    {%block header%}

    {%endblock%}


    {%block content%}

    {%endblock content%}	
	
<!--===============================================================================================-->
	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/daterangepicker/moment.min.js"></script>
	<script src="vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
    <script src={% static 'js/main.js' %}></script>


</body>
</html>

documenter/templates/documenter/_partials/documenter.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Documenter - Page</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/iconic/css/material-design-iconic-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/noui/nouislider.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="css/util.css">
	<link rel="stylesheet" type="text/css" href="css/maindocu.css">
<!--===============================================================================================-->
</head>
<body>


	<div class="container-contact100">
		<div class="wrap-contact100">
			<form class="contact100-form validate-form">
				<span class="contact100-form-title">
					Document Solutions
				</span>
				<div class="wrap-input100 validate-input bg1" data-validate="Please Enter the title here!">
					<span class="label-input100">Title *</span>
					<input class="input100" type="text" name="name" placeholder="Enter the title here">
				</div>

				<div class="wrap-input100 input100-select bg1">
					<span class="label-input100">Tag a Unit *</span>
					<div>
						<select class="js-select2" name="service">
                                        <option>Select Units</option>
						</select>
						<div class="dropDownSelect2"></div>
					</div>
				</div>

				<div class="w-full dis-none js-show-service">
					<div class="wrap-contact100-form-radio">
						<span class="label-input100">Tag Unit</span>

						<div class="contact100-form-radio m-t-15">
							<input class="input-radio100" id="radio1" type="radio" name="type-product" value="physical" checked="checked">
							<label class="label-radio100" for="radio1">
								All
							</label>
						</div>
						<div class="contact100-form-radio">
							<input class="input-radio100" id="radio2" type="radio" name="type-product" value="physical" checked="checked">
							<label class="label-radio100" for="radio2">
								X3 Technical
							</label>
						</div>
						<div class="contact100-form-radio">
							<input class="input-radio100" id="radio3" type="radio" name="type-product" value="digital">
							<label class="label-radio100" for="radio3">
								X3 Functional
							</label>
						</div>

						<div class="contact100-form-radio">
							<input class="input-radio100" id="radio4" type="radio" name="type-product" value="service">
							<label class="label-radio100" for="radio4">
								X3 People
							</label>
						</div>
						<div class="contact100-form-radio">
							<input class="input-radio100" id="radio5" type="radio" name="type-product" value="service">
							<label class="label-radio100" for="radio5">
								Evolution
							</label>
						</div>
					</div>
				</div>
				<div class="wrap-input100 validate-input bg0 rs1-alert-validate" data-validate = "Please Type Your Message">
					<span class="label-input100">Description</span>
					<textarea class="input100" name="message" placeholder="Your detailed solution here..."></textarea>
				</div>
				<div class="wrap-input100 validate-input bg0 rs1-alert-validate">
					<label for="formFileMultiple" class="label-input100">Upload Image(s) *</label>
					<input class="input100" type="file" id="formFileMultiple" multiple>
				</div>
				
				<div class="container-contact100-form-btn">
					<button class="contact100-form-btn">
						<span>
							Submit
							<i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
						</span>
					</button>
				</div>
			</form>
		</div>
	</div>



<!--===============================================================================================-->
	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
	<script>
		$(".js-select2").each(function(){
			$(this).select2({
				minimumResultsForSearch: 20,
				dropdownParent: $(this).next('.dropDownSelect2')
			});


			$(".js-select2").each(function(){
				$(this).on('select2:close', function (e){
					if($(this).val() == "Please chooses") {
						$('.js-show-service').slideUp();
					}
					else {
						$('.js-show-service').slideUp();
						$('.js-show-service').slideDown();
					}
				});
			});
		})
	</script>
<!--===============================================================================================-->
	<script src="vendor/daterangepicker/moment.min.js"></script>
	<script src="vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->

<!--===============================================================================================-->
	<script src="js/main3.js"></script>


</body>
</html>

documenter/templates/documenter/_partials/home.html
{% load static %}

<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="author" content="documenter">
    <link rel="icon" type="image/png" href={% static 'images/icons/favicon.ico' %}/>
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href={% static 'css/main2.css' %}>
    <!-- <link href="css/main2.css" rel="stylesheet" /> -->
  </head>
  <body>
    {%include 'documenter/_partials/navbar.html'%}
    <div class="s130">
      <form method="POST">
        {% csrf_token %}
        <div class="inner-form">
          <div class="input-field first-wrap">
            <div class="svg-wrapper">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"></path>
              </svg>
            </div>
            <input id="search" type="text" placeholder="What are you looking for?" />
          </div>
          <div class="input-field second-wrap">
            <button class="btn-search" type="button">SEARCH</button>
          </div>
        </div>
        <span class="info">ex. X3, Evolution, X3 People, Evolution</span>
      </form>
    </div>
    <script src={% static 'js/extention/choices.js' %}></script>
    <!-- <script src="js/extention/choices.js"></script> -->
  </body>
</html>

documenter/templates/documenter/_partials/nav2.html
<nav class="navbar navbar-dark bg-dark navbar-expand-sm">
    <a class="navbar-brand" href="#">
      <img src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/logo_white.png" width="30" height="30" alt="logo">
      BootstrapBay
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar-list-4">
      <ul class="navbar-nav">
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/fox.jpg" width="40" height="40" class="rounded-circle">
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Dashboard</a>
            <a class="dropdown-item" href="#">Edit Profile</a>
            <a class="dropdown-item" href="#">Log Out</a>
          </div>
        </li>   
      </ul>
    </div>
  </nav>

  

documenter/templates/documenter/_partials/navbar.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="robots" content="noindex, nofollow"> 

    <title>Documenter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
	<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
	<link rel="stylesheet" href= "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href={% static '/css/nav.css' %}>
	<link rel="stylesheet" type="text/css" href={% static '/css/button.css' %}>
    <!-- <link media="all" type="text/css" rel="stylesheet" href="/css/nav.css"> -->

</head>
<body>

	<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="#">Documenter</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav navbar-right">
			
			<li><a href="#">Document Solution</a></li>
			<li><a href="{% url "documenter:document" %}" class="btn btn-accent btn-action-lg btn-raised"><i class="material-icons">add</i></a></li>

			<li><a href="">Welcome {{user.last_name}}</a></li>	
			<ul class="nav navbar-nav">
				<!-- <li><a href="#"><i class="fa fa-bell-o fa-lg" aria-hidden="true"></i></a></li> -->
				<li><a href="#"><i class="fa fa-envelope-o fa-lg" aria-hidden="true"></i></a></li>
			</ul>
			<li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
				<!-- <a class="dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				<img src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/fox.jpg" width="40" height="40" class="rounded-circle">
			    </a> -->
			<ul class="dropdown-menu">
				
				<li><a href="{ % url "accounts:change_profile" % }"><i class="fa fa-user fa-lg" aria-hidden="true"></i> Profile </a></li>
				<li role="separator" class="divider"></li>
				<!-- <li><a href="#"><i class="fa fa-book fa-lg" aria-hidden="true"></i></i> Accessment</a></li>
				<li role="separator" class="divider"></li> -->
				<li><a href="{ % url "accounts:change_profile" % }"><i class="fa fa-tools fa-lg" aria-hidden="true"></i> Settings</a></li>
				<li role="separator" class="divider"></li>
				<li><a href="{% url "accounts:logout" %}"><i class="fa fa-tools fa-lg" aria-hidden="true"></i> Log Out</a></li>
			</ul>
			</li>
		</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
	</nav>
    <script type="text/javascript">
    (function($) { 
        $('#theme_chooser').change(function(){
            whichCSS = $(this).val();
            document.getElementById('snippet-preview').contentWindow.changeCSS(whichCSS);
        });
    })(jQuery);
    </script>
</body>
</html>